name: netlify-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v3.8.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Deploy to Netlify
        run: |
         npm install netlify-cli -g
         netlify deploy --prod --dir=public
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}